### ISSUE TITLE
Mixins with 0 arguments are not transformed properly

### ISSUE THREAD

**Issue by AndyOGo** [ekryski/less2sass#13]
This:

``` less
.foo() {
  display: block;
}
```

 should be transformed to:

``` scss
@mixin foo() {
  display: block;
}
```

but it is not
