### ISSUE TITLE
extends are not transformed

### ISSUE THREAD

**Issue by AndyOGo** [ekryski/less2sass#14]
[Less extends](http://lesscss.org/features/#extend-feature) is not transformed to `@extend`

E.g. this:

``` less
.foo {
  display: block;
}

.bar {
  &:extend(.foo);
}
```

should become this:

``` scss
.bar {
  @extend .foo;
}
```
